version: "3.9"

services:
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8080:4010"
    command: mock -h 0.0.0.0 /openapi.json
    volumes:
      - ./apis/openapi.json:/openapi.json

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./apis/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
